---
title: "Data visual"
output: html_document
---

Data visualization and overview

```{r}
library(tidyverse)
library(ggplot2)
data = read.csv('Metro_Interstate_Traffic_Volume.csv')
```


```{r,message=FALSE, warning=FALSE}

#distribution of y
ggplot(data= data, aes(x = traffic_volume)) + 
  geom_histogram(aes(y=..density..),color="darkblue", fill="lightblue") +
  geom_density()+
  labs(title="Distribution of Traffic Volume",x="Traffic Volume", y = "Density")

#how holiday influence y
ggplot(data = data[data$holiday!='None',], aes(group = holiday, y=traffic_volume,color=holiday )) +
  geom_boxplot()+
  labs(title="Holiday v.s. Traffic Volume",y="Traffic Volume", color = "Holiday")
```

```{r,message=FALSE, warning=FALSE}
library(corrplot)
library(RColorBrewer)
library(lubridate)

#extract hour from date_time
data$date_time <- hour(data$date_time)
#change categorical data to factor numbers
data[,c(1,6,7)] <- data[,c(1,6,7)] %>% mutate_if(is.factor, as.numeric)

#correlation coefficients
M <-cor(data)
corrplot(M, type="upper",method="color",
         addCoef.col = "black", order="hclust", number.cex= 7/ncol(data),
         tl.col="black", tl.srt=45,tl.cex = .85,
         p.mat = cor.mtest(data)$p, sig.level = 0.1, insig = "blank",
         diag=FALSE, col=brewer.pal(n=8, name="PuOr"))


```

Reference
```{r}
#http://www.sthda.com/english/wiki/visualize-correlation-matrix-using-correlogram
#http://www.sthda.com/english/wiki/ggplot2-histogram-plot-quick-start-guide-r-software-and-data-visualization
```

