---
title: "STA 141C Final Project R Markdown"
author: "Yutian Yang & Xin Ye & Xinyue Wang & Falak Shah"
date: "3/10/2020"
output: html_document
---

```{r}
Metro_Interstate_Traffic_Volume <- read.csv("Metro_Interstate_Traffic_Volume.csv")
attach(Metro_Interstate_Traffic_Volume)
library(dplyr)
library(ggpubr)
library(tidyr)
library(tidyverse)
library(ggplot2)
```


```{r}
library(car)
library(GGally)

##Import dataset and split date into month, day, and time
Metro <- read_csv("Metro_Interstate_Traffic_Volume.csv")
New_Metro = separate(Metro, date_time, c("date","time"), sep = " ", remove = TRUE,
  convert = FALSE, extra = "warn", fill = "warn")
New_Metro = separate(New_Metro, date, c("year","month","day"), sep = "-", remove = TRUE,
  convert = FALSE, extra = "warn", fill = "warn")
summary(New_Metro)
## plot the correlation bewteen variables to see if there are interactions.
#ggcorr(New_Metro)

#distribution of y
ggplot(data= New_Metro, aes(x = traffic_volume)) + 
  geom_histogram(aes(y=..density..),color="darkblue", fill="lightblue") +
  geom_density()+
  labs(title="Distribution of Traffic Volume",x="Traffic Volume", y = "Density")
ggqqplot(Metro$traffic_volume,main = "QQ plot for traffic volumn")
#how holiday influence y
ggplot(data = New_Metro[New_Metro$holiday!='None',], aes(group = holiday, y=traffic_volume,color=holiday )) +
  geom_boxplot()+
  labs(title="Holiday v.s. Traffic Volume",y="Traffic Volume", color = "Holiday")

#how weather influence y
ggplot(data = New_Metro, aes(group = weather_main, y=traffic_volume,color=weather_main )) +
  geom_boxplot()+
  labs(title="Weather Main v.s. Traffic Volume",y="Traffic Volume", color = "weather_main")

#how hour influence y
ggplot(data = New_Metro, aes(group = time, y=traffic_volume,color=time )) +
  geom_boxplot()+
  labs(title="Hours v.s. Traffic Volume",y="Traffic Volume", color = "Time")

#how year influence y
ggplot(data = New_Metro, aes(group = year, y=traffic_volume,color=year )) +
  geom_boxplot()+
  labs(title="Year v.s. Traffic Volume",y="Traffic Volume", color = "Year")

#how month influence y
ggplot(data = New_Metro, aes(group = month, y=traffic_volume,color= month )) +
  geom_boxplot()+
  labs(title="Month v.s. Traffic Volume",y="Traffic Volume", color = "Month")
```


```{r}

library(corrplot)
library(RColorBrewer)
library(lubridate)
data = Metro
#extract hour from date_time
data$date_time <- hour(data$date_time)

#correlation coefficients
M <-cor(data[,-c(1,6,7)])
corrplot(M, type="upper",method="color",
         addCoef.col = "black", order="hclust", number.cex= 7/ncol(data[,-c(1,6,7)]),
         tl.col="black", tl.srt=45,tl.cex = .85,
         p.mat = cor.mtest(data[,-c(1,6,7)])$p, sig.level = 0.1, insig = "blank",
         diag=FALSE, col=brewer.pal(n=8, name="PuOr"))
```


```{r}
##Linear Model Selection
lm1 = lm(traffic_volume~ temp + clouds_all + as.factor(weather_main),data = New_Metro)
### Combining AIC, BIC and linear model selection to select the prediction model.
AIC(lm1)
BIC(lm1)
summary(lm1)
###Factor Time is significant
lm2 = lm(traffic_volume~ temp + clouds_all + as.factor(time),data = New_Metro)
summary(lm2)
AIC(lm2)
BIC(lm2)
plot(lm2)
hist(lm2$residuals)
### Another possible model
lm3 = lm(traffic_volume~ temp + clouds_all + as.factor(time) + as.factor(weather_main),data = New_Metro)
AIC(lm3)
BIC(lm3)
summary(lm3)

```



```{r}

## Demean the traffic volume since it is the dominant factor
Metro_without_time = New_Metro %>%
  group_by(time)%>%
  filter(temp != 0.00) %>%
  mutate( new_traffic_volume = traffic_volume - mean(traffic_volume))


## New linear Model
lm4 = lm(new_traffic_volume~ temp + clouds_all + as.factor(weather_main),data = Metro_without_time)
AIC(lm4)
BIC(lm4)
summary(lm4)
lm4$coefficients
plot(lm4)


## Demean the weather factor
Metro_without_time_weather = Metro_without_time%>%
  group_by(weather_main)%>%
  mutate(new_traffic_volume2 = new_traffic_volume - mean(new_traffic_volume))

lm5 = lm(new_traffic_volume2~ temp + clouds_all,data = Metro_without_time_weather)
summary(lm5)
AIC(lm5)
BIC(lm5)
plot(lm5)
hist(lm5$residuals)

write_csv(Metro_without_time_weather,"Metro_without_time_weather.csv")
```


```{r,echo = FALSE}

## Using parallelization to bootstrap
library(parallel)
cl = makeCluster(4)
B = 1000
predict_newdata <- function(data){
  model = lm(data$traffic_volume~data$temp+data$clouds_all)
  coefficient = model$coefficients
  y = coefficient[[1]] + coefficient[[2]]* data$temp + coefficient[[3]]* data$clouds_all
}
singleBoots <- function(i){
  index = sample(x = seq_len(n), size = n, replace = TRUE)
  data_star = data[index,]
  predict_newdata(data_star)
}
clusterEvalQ(cl,{
  library(tidyverse)
  data <- read_csv("Metro_without_time_weather.csv")
  n <- length(data$traffic_volume)
  predict_newdata <- function(data){
  model = lm(data$traffic_volume~data$temp+data$clouds_all)
  coefficient = model$coefficients
  y = coefficient[[1]] + coefficient[[2]]* data$temp + coefficient[[3]]* data$clouds_all
}
})
predict_newdata = parSapply(cl, seq_len(B),singleBoots)
predict_newdata %>% quantile(c(0.025,0.975))
stopCluster(cl)
```

```{r,echo = FALSE}
cl = makeCluster(4)
B =1000
coef_beta0 <- function(data){
  model = lm(data$traffic_volume~data$temp+data$clouds_all)
  coefficient = model$coefficients[[1]]
}
singleBoots <- function(i){
  index = sample(x = seq_len(n), size = n, replace = TRUE)
  data_star = data[index,]
  coef_beta0(data_star)
}
clusterEvalQ(cl,{
  library(tidyverse)
  data <- read_csv("Metro_without_time_weather.csv")
  n <- length(data$traffic_volume)
  coef_beta0 <- function(data){
  model = lm(data$traffic_volume~data$temp+data$clouds_all)
  coefficient = model$coefficients[[1]]
}
})
beta0_ci = parSapply(cl, seq_len(B),singleBoots)
beta0_ci %>% quantile(c(0.025,0.975))
stopCluster(cl)
```

```{r,echo = FALSE}
cl = makeCluster(4)
B =1000
coef_beta1 <- function(data){
  model = lm(data$traffic_volume~data$temp+data$clouds_all)
  coefficient = model$coefficients[[2]]
}
singleBoots <- function(i){
  index = sample(x = seq_len(n), size = n, replace = TRUE)
  data_star = data[index,]
  coef_beta1(data_star)
}
clusterEvalQ(cl,{
  library(tidyverse)
  data <- read_csv("Metro_without_time_weather.csv")
  n <- length(data$traffic_volume)
  coef_beta1 <- function(data){
  model = lm(data$traffic_volume~data$temp+data$clouds_all)
  coefficient = model$coefficients[[2]]
}
})
beta1_ci = parSapply(cl, seq_len(B),singleBoots)
beta1_ci %>% quantile(c(0.025,0.975))
stopCluster(cl)
```

```{r}
cl = makeCluster(4)
B = 1000
coef_beta2 <- function(data){
  model = lm(data$traffic_volume~data$temp+data$clouds_all)
  coefficient = model$coefficients[[3]]
}
singleBoots <- function(i){
  index = sample(x = seq_len(n), size = n, replace = TRUE)
  data_star = data[index,]
  coef_beta2(data_star)
}
clusterEvalQ(cl,{
  library(tidyverse)
  data <- read_csv("Metro_without_time_weather.csv")
  n <- length(data$traffic_volume)
  coef_beta2 <- function(data){
  model = lm(data$traffic_volume~data$temp+data$clouds_all)
  coefficient = model$coefficients[[3]]
}
})
beta1_ci = parSapply(cl, seq_len(B),singleBoots)
beta1_ci %>% quantile(c(0.025,0.975))
stopCluster(cl)
```



